language: perl
perl:
  - "5.8"
  - "5.8.7"
  - "5.8.7-thr"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.18.1-thr"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "dev"
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
install:
  - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=c HARNESS_TIMER=1
  - cpanm --quiet --notest --installdeps .
script:
  - cd test && test.sh
