language: perl
perl:
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"
  - "5.30"
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --auto
script: cd test && test.sh
